# Notebook 01
<img src="images/python_numpy.png">

## Introduction to Numpy
1. Numpy is an <b>open-source</b> library for the scientific computing in Python.
2. It provides with the high-performance multi-dimensional array objects called <b>ndarray</b>.
3. It provides you with a large collection of functions to operate on these arrays.
4. It is used in Image Processing, Signal Processing, Linear Algebra etc.
5. One of the fundamental library for the data science.

In [1]:
import numpy as np

# 1D

In [2]:
x = np.array([1, 2, 3], dtype=np.int16)
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(x[0]); print(x[1]); print(x[2])

1
2
3


In [4]:
print(x[-1]); print(x[-2]); print(x[-3])

3
2
1


In [6]:
print(x[-4])

IndexError: index -4 is out of bounds for axis 0 with size 3

# 2D

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
print(x)

[[1 2 3]
 [4 5 6]]


In [8]:
print(x[0, 0]); print(x[0, 1]); print(x[0, 2])

1
2
3


In [9]:
print(x[1, 0]); print(x[1, 1]); print(x[1, 2])

4
5
6


In [10]:
print(x[:, 0])

[1 4]


In [11]:
print(x[:, 1]); print(x[:, 2])

[2 5]
[3 6]


In [13]:
print(x[0, :]); print(x[1, :])

[1 2 3]
[4 5 6]


# 3D

In [14]:
x = np.array([[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], dtype=np.int16)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [15]:
print(x[0, 0, 0])

1


In [16]:
print(x[0, 0, 3])

IndexError: index 3 is out of bounds for axis 2 with size 3

In [18]:
print(x[0, 0, 2])

3


In [19]:
print(x[1, 1, 2])

-5


In [20]:
print(x[:, :, 0])

[[ 1  4]
 [ 0 -3]]


In [21]:
print(x[:, 0, 0])

[1 0]
