# Notebook 02: Properties of Numpy Array

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3], dtype=np.int16)
y = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)

In [3]:
print(x)

[1 2 3]


In [4]:
print(y)

[[1 2 3]
 [4 5 6]]


### 1. Shape

In [5]:
print(x.shape); print(y.shape)

(3,)
(2, 3)


### 2. Number of dimensions

In [6]:
print(x.ndim); print(y.ndim)

1
2


### 3. Datatype

In [7]:
print(x.dtype); print(y.dtype)

int16
int16


### 4. SIze (Total number of elements)

In [8]:
print(x.size); print(y.size)

3
6


### 5. SIze in terms of bytes

In [9]:
print(x.nbytes); print(y.nbytes)

6
12


### 6. Transpose

In [10]:
print(x.T)

[1 2 3]


In [11]:
print(y.T)

[[1 4]
 [2 5]
 [3 6]]
